### PR TITLE
Be friendly to SBT plugins that also use URLHandlerRegistry.setDefault

### PR DESCRIPTION
**Pull request by tpunder**
Other plugins (for example: https://github.com/frugalmechanic/fm-sbt-s3-resolver)
also make use of the URLHandlerRegistry.setDefault mechanism to register handlers
for other protocols (e.g. "s3").  This change makes it so that SBT will only
register the http/https protocols and will preserve any other protocol handlers
that have already been registered.

**NOTE: This has now been tested and fixes https://github.com/sbt/librarymanagement/issues/175**

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?librarymanagement=pull/183/head&deploy_to_bintray=false&run_sbt_community=false">this link.</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/280/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: 1.x-1.x-1.x-pull/183/head-1.x-1.x)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/280/">has checked</A> the following projects against Scala 2.12,
tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/1.x">1.x                 </A> | sbt/sbt@8b1cab04c6cfc1f942c0c5ea36d1ae90f551d424
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/1.x">1.x                 </A> | sbt/zinc@b1e7eacc6940855f05d7a8d28a037013f64ee4c2
  io                | <A HREF="https://github.com/sbt/io/tree/1.x">1.x                 </A> | sbt/io@e8c9757799bb0b251e5c5aefd96f841428d0eb9a
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/pull/183">pull/183/head       </A> | sbt/librarymanagement@8330d164316540b4b6aba89b5833a0c96a9035e9
  util              | <A HREF="https://github.com/sbt/util/tree/1.x">1.x                 </A> | sbt/util@f4eadfc259f6f25b61eeb519fe29fb44220bec4a
  website           | <A HREF="https://github.com/sbt/website/tree/1.x">1.x                 </A> | 

:white_check_mark: The result is: ***SUCCESS***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=1.x&zinc=1.x&io=1.x&librarymanagement=pull/183/head&util=1.x&website=1.x&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by tpunder** [comment]
I've now tested this fix and it resolves the conflict with fm-sbt-s3-resolver.

Here is what I did:

- Built sbt/librarymanagement locally and did a `publishLocal`
- Build sbt/sbt locally (using `sbt -Dsbtlm.path=../librarymanagement`) and did a `publishLocal`
- Updated my project using fm-sbt-s3-resolver to use my `-SNAPSHOT` version of sbt
- Cleared my `.ivy/cache`
- Verified my project still downloaded all dependencies
- Published my project using the fm-sbt-s3-resolver plugin.  **This now works!  It previously failed.**
- Repeated the previous steps for my project using both `sbt -Dsbt.gigahorse=true` and `sbt -Dsbt.gigahorse=false`

So from my standpoint everything looks good!

**Review by dwijnand — APPROVED** [review]
Excellent work, thank you @tpunder!

**Review by eed3si9n — APPROVED** [review]
Thanks for the contribution!

**Comment by eed3si9n** [comment]
I'm retargeting this to 1.0.x branch so we can include this in sbt 1.0.x.
Luckily other commits seems like fixes too.

**Pull request merged**
