### PR TITLE
Enable Gigahorse configuration

### PR DESCRIPTION
**Pull request by rdesgroppes**
This allows using `application.conf` if present, where Gigahorse configuration might be defined, see: http://eed3si9n.com/gigahorse/configuration.html#Configuring+Gigahorse

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=develop&zinc=develop&io=develop&librarymanagement=pull/289/head&util=develop&website=develop&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1346/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: 1.2.x-1.2.x-1.2.x-pull/289/head-1.2.x)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1346/">has checked</A> the following projects, tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/1.2.x">1.2.x               </A> | sbt/sbt@9e37391937b2d262dfb93325074dc692824519d1
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/1.2.x">1.2.x               </A> | sbt/zinc@c46643f3e68d7d4f270bf318e3f150f5a59c0aab
  io                | <A HREF="https://github.com/sbt/io/tree/1.2.x">1.2.x               </A> | sbt/io@628d8738070bb65356349630e56cac5c83707c70
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/pull/289">pull/289/head       </A> | sbt/librarymanagement@76ba151837656f62c7affdf105ee868425e3120d
  util              | <A HREF="https://github.com/sbt/util/tree/1.2.x">1.2.x               </A> | sbt/util@016858ddd8601f9d55224d2b6ec9b046cf8e29d9

:white_check_mark: The result is: ***SUCCESS***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=1.2.x&zinc=1.2.x&io=1.2.x&librarymanagement=pull/289/head&util=1.2.x&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Review by eed3si9n — CHANGES_REQUESTED** [review]
librarymanagement used to be coded that way, but then it was changed in https://github.com/sbt/librarymanagement/pull/241 to current code to workaround an issue.

**Pull request closed without merging**
