### PR TITLE
Fix OkHttp JavaNetAuthenticator with null check

### PR DESCRIPTION
**Pull request by eed3si9n**
Fixes https://github.com/sbt/sbt/issues/3519

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?librarymanagement=pull/177/head&deploy_to_bintray=false&run_sbt_community=false">this link.</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/242/console">is in progress...</a>

**Comment by eed3si9n** [comment]
I just created a branch on sbt/sbt-standalone-build without the gigahorse=false flag -  https://github.com/sbt/sbt-standalone-build/commit/b2c3daa4aa6e77b2c68d7c009f7ecaa3d4fb10c4

**Comment by dwijnand** [comment]
I wish the "fix" was more sophisticated.. Do we have any understanding what the cause is?

**Comment by typesafe-tools** [comment]
[//]: # (Refs: 1.x-1.x-1.x-pull/177/head-1.x-1.x)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/242/">has checked</A> the following projects against Scala 2.12,
tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/1.x">1.x                 </A> | sbt/sbt@d5e1de08aaf07014527459e8be31c5d5ba082ebb
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/1.x">1.x                 </A> | sbt/zinc@59bc417ff4b608d4513ec1dc83b344cd095dfa11
  io                | <A HREF="https://github.com/sbt/io/tree/1.x">1.x                 </A> | sbt/io@e8c9757799bb0b251e5c5aefd96f841428d0eb9a
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/pull/177">pull/177/head       </A> | sbt/librarymanagement@a28d7f0d226caa72fba4fb525aff826d5ae0e2dc
  util              | <A HREF="https://github.com/sbt/util/tree/1.x">1.x                 </A> | sbt/util@f4eadfc259f6f25b61eeb519fe29fb44220bec4a
  website           | <A HREF="https://github.com/sbt/website/tree/1.x">1.x                 </A> | 

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=1.x&zinc=1.x&io=1.x&librarymanagement=pull/177/head&util=1.x&website=1.x&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by eed3si9n** [comment]
Maybe a better fix is putting `null` check around https://github.com/square/okhttp/blob/parent-3.7.0/okhttp-urlconnection/src/main/java/okhttp3/JavaNetAuthenticator.java#L37

**Comment by eed3si9n** [comment]
Also Dbuild is saying that a28d7f0 didn't fix.

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/243/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: 1.x-1.x-1.x-pull/177/head-1.x-1.x)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/243/">has checked</A> the following projects against Scala 2.12,
tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/1.x">1.x                 </A> | sbt/sbt@d5e1de08aaf07014527459e8be31c5d5ba082ebb
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/1.x">1.x                 </A> | sbt/zinc@59bc417ff4b608d4513ec1dc83b344cd095dfa11
  io                | <A HREF="https://github.com/sbt/io/tree/1.x">1.x                 </A> | sbt/io@e8c9757799bb0b251e5c5aefd96f841428d0eb9a
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/pull/177">pull/177/head       </A> | sbt/librarymanagement@8cec3a90b6767671e7a81c7bb8089a2729fb1307
  util              | <A HREF="https://github.com/sbt/util/tree/1.x">1.x                 </A> | sbt/util@f4eadfc259f6f25b61eeb519fe29fb44220bec4a
  website           | <A HREF="https://github.com/sbt/website/tree/1.x">1.x                 </A> | 

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=1.x&zinc=1.x&io=1.x&librarymanagement=pull/177/head&util=1.x&website=1.x&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by eed3si9n** [comment]
oh lol. I just realized that Dbuild failure was not a failure on a28d7f0, but rather on the sbt 1.0.2 that it's using to build.

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/245/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: 1.x-1.x-1.x-pull/177/head-1.x-1.x)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/245/">has checked</A> the following projects against Scala 2.12,
tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/1.x">1.x                 </A> | sbt/sbt@8eb58791013b2826ab564d8c9e28275c7e7b2e6a
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/1.x">1.x                 </A> | sbt/zinc@59bc417ff4b608d4513ec1dc83b344cd095dfa11
  io                | <A HREF="https://github.com/sbt/io/tree/1.x">1.x                 </A> | sbt/io@e8c9757799bb0b251e5c5aefd96f841428d0eb9a
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/pull/177">pull/177/head       </A> | sbt/librarymanagement@91b00856627eae1e7ec0cba1098ef43353ae637c
  util              | <A HREF="https://github.com/sbt/util/tree/1.x">1.x                 </A> | sbt/util@f4eadfc259f6f25b61eeb519fe29fb44220bec4a
  website           | <A HREF="https://github.com/sbt/website/tree/1.x">1.x                 </A> | 

:white_check_mark: The result is: ***SUCCESS***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=1.x&zinc=1.x&io=1.x&librarymanagement=pull/177/head&util=1.x&website=1.x&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/246/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: 1.x-1.x-1.x-pull/177/head-1.x-1.x)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/246/">has checked</A> the following projects against Scala 2.12,
tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/1.x">1.x                 </A> | sbt/sbt@8eb58791013b2826ab564d8c9e28275c7e7b2e6a
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/1.x">1.x                 </A> | sbt/zinc@59bc417ff4b608d4513ec1dc83b344cd095dfa11
  io                | <A HREF="https://github.com/sbt/io/tree/1.x">1.x                 </A> | sbt/io@e8c9757799bb0b251e5c5aefd96f841428d0eb9a
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/pull/177">pull/177/head       </A> | sbt/librarymanagement@91b00856627eae1e7ec0cba1098ef43353ae637c
  util              | <A HREF="https://github.com/sbt/util/tree/1.x">1.x                 </A> | sbt/util@f4eadfc259f6f25b61eeb519fe29fb44220bec4a
  website           | <A HREF="https://github.com/sbt/website/tree/1.x">1.x                 </A> | 

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=1.x&zinc=1.x&io=1.x&librarymanagement=pull/177/head&util=1.x&website=1.x&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by eed3si9n** [comment]
Why was this closed?

**Comment by dwijnand** [comment]
It auto-closed because I deleted the 1.0.x branch. Sorry, I should remember that of this effect.

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?librarymanagement=pull/177/head&deploy_to_bintray=false&run_sbt_community=false">this link.</A>

**Comment by denisgarci** [comment]
Any updates on this fix? This bug is blocking to update to sbt `1.1.x`. Thanks!

**Comment by dwijnand** [comment]
Closing as it's stale and failing CI.

The underlying issue is still tracked as https://github.com/sbt/sbt/issues/3519 and there's a link from that to this, so this work can be recovered, revisited and resubmitted.

**Comment by eed3si9n** [comment]
This PR actually addresses one of the known patterns of NPE that was reported https://github.com/sbt/sbt/issues/3519#issuecomment-331395080
Maybe we should:
1. Merge this PR once it passes the tests. (I don't think failures are related to this)
2. and send the patch upstream.

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=1.1.x&zinc=1.1.x&io=1.1.x&librarymanagement=pull/177/head&util=1.1.x&website=1.1.x&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/774/console">is in progress...</a>

**Comment by eed3si9n** [comment]
The stacktrace says:

```
[error] java.lang.NullPointerException
[error] 	at okhttp3.JavaNetAuthenticator.authenticate(JavaNetAuthenticator.java:37)
[error] 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.followUpRequest(RetryAndFollowUpInterceptor.java:284)
...
```

okhttp code says:

```java
    Proxy proxy = route.proxy();
```

What this PR adds:

```diff
+    Proxy proxy = null;
+    if (route != null) {
+      proxy = route.proxy();
+    }
```

**Comment by eed3si9n** [comment]
Travis CI is a go:

build__709_-_sbt_librarymanagement_-_travis_ci

**Review by dwijnand — APPROVED** [review]

**Comment by typesafe-tools** [comment]
[//]: # (Refs: 1.1.x-1.1.x-1.1.x-pull/177/head-1.1.x-1.1.x)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/774/">has checked</A> the following projects against Scala 2.12,
tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/1.1.x">1.1.x               </A> | sbt/sbt@17f5bc149ee13d12c22dc97c6d9414a626ff2085
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/1.1.x">1.1.x               </A> | sbt/zinc@899d7bd0282cf1ca2c0d3704ddb242bea30007e3
  io                | <A HREF="https://github.com/sbt/io/tree/1.1.x">1.1.x               </A> | sbt/io@1534128a10c3ae6c9f532432c95fa3440d755de5
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/pull/177">pull/177/head       </A> | sbt/librarymanagement@ac583b43c99e8f53a66fe72460c1c2b9a4b0bd30
  util              | <A HREF="https://github.com/sbt/util/tree/1.1.x">1.1.x               </A> | sbt/util@d40517b8280734ed236199a9cb8793c153597026
  website           | <A HREF="https://github.com/sbt/website/tree/1.1.x">1.1.x               </A> | 

:white_check_mark: The result is: ***SUCCESS***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=1.1.x&zinc=1.1.x&io=1.1.x&librarymanagement=pull/177/head&util=1.1.x&website=1.1.x&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Pull request merged**
