### PR TITLE
Bump to latest jsch to support stronger key exchange algorithms

### PR DESCRIPTION
**Pull request by ryandbair**
This fixes issues with SSH connections to GitHub following their removal of weak SSH key exchange ciphers.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=1.1.x&zinc=1.1.x&io=1.1.x&librarymanagement=pull/217/head&util=1.1.x&website=1.1.x&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Comment by ryandbair** [comment]
This also remove the intransitive property as discussed in #68

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/529/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: 1.1.x-1.1.x-1.1.x-pull/217/head-1.1.x-1.1.x)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/529/">has checked</A> the following projects against Scala 2.12,
tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/1.1.x">1.1.x               </A> | sbt/sbt@27bbde810d933a8ae769840373680b9442ee29a6
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/1.1.x">1.1.x               </A> | sbt/zinc@6a7acaaaa38836556bc8b3012a1d6cabfb46ce44
  io                | <A HREF="https://github.com/sbt/io/tree/1.1.x">1.1.x               </A> | sbt/io@13eb241853180bdbb0d009ce11db5443749615d2
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/pull/217">pull/217/head       </A> | sbt/librarymanagement@14cc5ea626762a82205c581de5f453e7e13c7bc7
  util              | <A HREF="https://github.com/sbt/util/tree/1.1.x">1.1.x               </A> | sbt/util@226a543f927de44016f17a28d30aa6263c4abd04
  website           | <A HREF="https://github.com/sbt/website/tree/1.1.x">1.1.x               </A> | 

:white_check_mark: The result is: ***SUCCESS***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=1.1.x&zinc=1.1.x&io=1.1.x&librarymanagement=pull/217/head&util=1.1.x&website=1.1.x&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Review by eed3si9n — APPROVED** [review]

**Comment by eed3si9n** [comment]
Thanks for the contribution!

**Pull request merged**
