### PR TITLE
Override scala organization and version transitively at the Ivy level

### PR DESCRIPTION
**Pull request by milessabin**
Forward port from 0.13.x.

### CODE REVIEW

**Comment by dwijnand** [comment]
:+1: thank you

**Comment by milessabin** [comment]
Needs a corresponding change in sbt 1.0.x ... I'm on that now.

**Comment by milessabin** [comment]
See also: https://github.com/sbt/sbt/pull/2635.

**Comment by eed3si9n** [comment]
Merged

**Pull request merged**
