### PR TITLE
Fix toString

### PR DESCRIPTION
**Pull request by eed3si9n**
Ref https://github.com/sbt/librarymanagement/pull/6

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?librarymanagement=pull/120/head&deploy_to_bintray=false">THIS LINK.</A>

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/73/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: 1.0.x-pull/323/head-1.0-pull/120/head-1.0-1.0.x)
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/73/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | 1.0.x                | sbt/sbt@25d393bd8b34e3bf72d129c2427349c7aa881701
  zinc              | pull/323/head        | sbt/zinc@eea913511e979740037259a0196125a9d994bc73
  io                | 1.0                  | sbt/io@177ba25c18fb280fb8afd660b72dfa0bc59f83d1
  librarymanagement | pull/120/head        | sbt/librarymanagement@6953cb09a917690b64e744bf881fd964ba15709c
  util              | 1.0                  | sbt/util@54cf4a43bb560d2e6fdc48fb51a376ca4228da03
  website           | 1.0.x                | sbt/website@5c32a0afcf64dc600ff154f5456026e2a74dc668

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild?sbt=1.0.x&zinc=pull/323/head&io=1.0&librarymanagement=pull/120/head&util=1.0&website=1.0.x&deploy_to_bintray=false">(restart)</A>

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/74/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/3295/head-pull/323/head-1.0-pull/120/head-1.0-1.0.x)
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/74/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | pull/3295/head       | sbt/sbt@0774a248e7c1081f236b9be6aa14363b940221cc
  zinc              | pull/323/head        | sbt/zinc@eea913511e979740037259a0196125a9d994bc73
  io                | 1.0                  | sbt/io@177ba25c18fb280fb8afd660b72dfa0bc59f83d1
  librarymanagement | pull/120/head        | sbt/librarymanagement@6953cb09a917690b64e744bf881fd964ba15709c
  util              | 1.0                  | sbt/util@54cf4a43bb560d2e6fdc48fb51a376ca4228da03
  website           | 1.0.x                | sbt/website@5c32a0afcf64dc600ff154f5456026e2a74dc668

:white_check_mark: The result is: ***SUCCESS***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild?sbt=pull/3295/head&zinc=pull/323/head&io=1.0&librarymanagement=pull/120/head&util=1.0&website=1.0.x&deploy_to_bintray=false">(restart)</A>

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?librarymanagement=pull/120/head&deploy_to_bintray=false">THIS LINK.</A>

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?librarymanagement=pull/120/head&deploy_to_bintray=false">THIS LINK.</A>

**Review by dwijnand — APPROVED** [review]

**Pull request merged**
