### PR TITLE
avoid java.net.URL

### PR DESCRIPTION
**Pull request by jtjeferreira**
I was using sbt without internet connection and noticed that `update` task taking a lot of time (around 30s). I did a thread dump with a `SigQuit` ( `Ctrl` + `\`) and noticed that the thread was blocked because `java.net.URL#equals` blocks:

```
"pool-514-thread-3" #918 prio=5 os_prio=31 cpu=292.62ms elapsed=128.20s tid=0x000000012d484a00 nid=0x1071b waiting for monitor entry  [0x0000000175550000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.net.InetAddress$NameServiceAddresses.get(java.base@17.0.10/InetAddress.java:838)
	- waiting to lock <0x0000000737d5e758> (a java.net.InetAddress$NameServiceAddresses)
	at java.net.InetAddress.getAllByName0(java.base@17.0.10/InetAddress.java:1533)
	at java.net.InetAddress.getAllByName(java.base@17.0.10/InetAddress.java:1385)
	at java.net.InetAddress.getAllByName(java.base@17.0.10/InetAddress.java:1306)
	at java.net.InetAddress.getByName(java.base@17.0.10/InetAddress.java:1256)
	at java.net.URL.getHostAddress(java.base@17.0.10/URL.java:831)
	- locked <0x00000007073fd680> (a java.net.URL)
	at java.net.URLStreamHandler.getHostAddress(java.base@17.0.10/URLStreamHandler.java:447)
	at java.net.URLStreamHandler.hostsEqual(java.base@17.0.10/URLStreamHandler.java:459)
	at java.net.URLStreamHandler.sameFile(java.base@17.0.10/URLStreamHandler.java:431)
	at java.net.URLStreamHandler.equals(java.base@17.0.10/URLStreamHandler.java:352)
	at java.net.URL.equals(java.base@17.0.10/URL.java:980)
	at scala.runtime.BoxesRunTime.equals2(BoxesRunTime.java:137)
	at scala.runtime.BoxesRunTime.equals(BoxesRunTime.java:123)
	at scala.Some.equals(Option.scala:513)
	at sbt.librarymanagement.Artifact.equals(Artifact.scala:22)
	at scala.runtime.BoxesRunTime.equals2(BoxesRunTime.java:137)
	at scala.runtime.BoxesRunTime.equals(BoxesRunTime.java:123)
	at scala.Tuple2.equals(Tuple2.scala:24)
	at scala.runtime.BoxesRunTime.equals2(BoxesRunTime.java:137)
	at scala.runtime.BoxesRunTime.equals(BoxesRunTime.java:123)
	at scala.collection.IterableLike.sameElements(IterableLike.scala:304)
	at scala.collection.IterableLike.sameElements$(IterableLike.scala:294)
	at scala.collection.AbstractIterable.sameElements(Iterable.scala:56)
	at scala.collection.GenSeqLike.equals(GenSeqLike.scala:481)
	at scala.collection.GenSeqLike.equals$(GenSeqLike.scala:480)
	at scala.collection.AbstractSeq.equals(Seq.scala:45)
	at sbt.librarymanagement.ModuleReport.equals(ModuleReport.scala:34)
	at scala.runtime.BoxesRunTime.equals2(BoxesRunTime.java:137)
	at scala.runtime.BoxesRunTime.equals(BoxesRunTime.java:123)
	at scala.collection.IterableLike.sameElements(IterableLike.scala:304)
	at scala.collection.IterableLike.sameElements$(IterableLike.scala:294)
	at scala.collection.AbstractIterable.sameElements(Iterable.scala:56)
	at scala.collection.GenSeqLike.equals(GenSeqLike.scala:481)
	at scala.collection.GenSeqLike.equals$(GenSeqLike.scala:480)
	at scala.collection.AbstractSeq.equals(Seq.scala:45)
	at sbt.librarymanagement.ConfigurationReport.equals(ConfigurationReport.scala:21)
```

In this PR I tried to replace `java.net.URL` with `java.net.URI` in a backwards compatible manner in `Artifact`, `Developer`, and `ScmInfo`. 

Although I managed to make mima happy, I think there is a problem in the `Artifact#apply` method because it changed from having a parameter `url: Option[java.net.URL]` to `uri: Option[java.net.URI]` (which erases to `Option` and makes mima happy). I also cant add a new backwards compatible `apply` method because it would erase to the same signature.

Any ideas how to move forward?

### CODE REVIEW

**Comment by jtjeferreira** [comment]
@adpi2 I see you are working on #442. Do you think I can drop binary compatibility here?

**Comment by adpi2** [comment]
> @adpi2 I see you are working on https://github.com/sbt/librarymanagement/pull/442. Do you think I can drop binary compatibility here?

Yes, if you open a new PR to [wip/sbt-2.x](https://github.com/sbt/librarymanagement/tree/wip/sbt-2.x).

In sbt 1.x you should try not to break it and if you cannot, we should make sure it won't break any plugin out there.

**Comment by jtjeferreira** [comment]
> > @adpi2 I see you are working on #442. Do you think I can drop binary compatibility here?
> 
> Yes, if you open a new PR to [wip/sbt-2.x](https://github.com/sbt/librarymanagement/tree/wip/sbt-2.x?rgh-link-date=2024-05-29T12%3A07%3A59Z).

I will do that

> if you cannot, we should make sure it won't break any plugin out there.

how can I check if the change will break other plugins? There is some kind of community build?

**Comment by jtjeferreira** [comment]
@adpi2 I opened https://github.com/sbt/librarymanagement/pull/443

**Pull request closed without merging**
