### PR TITLE
Remove deprecated OkHTTP OkUrlFactory

### PR DESCRIPTION
**Pull request by dpratt**
- Replace usage of OkUrlFactory with just direct calls to the OkHTTP API. This allows us to ensure that connections get properly closed, and provides finer-grained internal control of how we make http requests.

- Ensure that exceptions/error status codes don't cause leaked or hanging connections. Previously, a 404 on an artifact download would cause the underlying OkHTTP client to keep the request and connection open. This has the effect of wasting resources, but also slowing down overall download/resolution time to non-pipelined HTTP servers.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?librarymanagement=pull/164/head&deploy_to_bintray=false">this link.</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/127/console">is in progress...</a>

**Comment by dpratt** [comment]
This fixes https://github.com/sbt/sbt/issues/3485

**Comment by eed3si9n** [comment]
Nice! I'm excited about this.

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?librarymanagement=pull/164/head&deploy_to_bintray=false">this link.</A>

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?librarymanagement=pull/164/head&deploy_to_bintray=false">this link.</A>

**Review by dwijnand — APPROVED** [review]
Nice! Thank you! LGTM

**Comment by eed3si9n** [comment]
I am wondering if this qualifies as hot fix 1.0.x as opposed to 1.x.

**Comment by dpratt** [comment]
@eed3si9n I tend to think so, but I'm just a civilian. We're currently running a fork of sbt 1.0.1 and librarymanagement 1.0.1 that has this patch in it, and I'd love to eliminate that.

**Comment by eed3si9n** [comment]
Merged to newly created 1.0.x branch.

**Pull request merged**
