### PR TITLE
Try resolve sbt plugin from valid Maven pattern

### LINKED ISSUE #3410: The maven pattern for sbt plugins is invalid based on the spec
I've been in touch with the Bintray team because of https://github.com/sbt/sbt-bintray/pull/125.
  
It happens that the reason why sbt bintray does not accept the fix in the aforementioned PR is because **sbt has been using an incorrect Maven pattern for sbt plugins**. This is the reply I got from the Bintray team:
  
> Going off of the Maven Design Documentation, Bintray expects the following Maven layout format:
`[orgPath]/[module]/[baseRev](-[folderItegRev])/[module]-[baseRev](-[fileItegRev])(-[classifier]).[ext]`. Note the “module” field appears twice.
  
Our pattern is the following: https://github.com/sbt/librarymanagement/blob/53c80f076a5e9ab469037f352a4d68173140e216/core/src/main/scala/sbt/librarymanagement/ResolverExtra.scala#L357-L358, which is obviously wrong (there's a concept of module and a concept of artifact, where both should be the same).
  
The reason why this works for Sonatype is because they have a permissive layout for projects whose publishing rules do not abide by the spec. Bintray doesn't, and that's why no one has succeeded to publish sbt plugins to Bintray maven repositories.
  
This is a major issue that IMO should be sorted out as soon as possible. The only way I see to solve this problem is to add another pattern to sbt and make it use alongside the wrong pattern (we cannot remove it, too many projects depend on it).

### PR DESCRIPTION
**Pull request by adpi2**
This PR is part of https://github.com/sbt/sbt/pull/7096 whose goal is to fix https://github.com/sbt/sbt/issues/3410 in a smooth way. For a full description please read https://github.com/sbt/sbt/pull/7096.

### CODE REVIEW

**Review by julienrf — COMMENTED** [review]
That looks great! Is it possible to test the resolution of sbt plugins?

**Comment by eed3si9n** [comment]
@adpi2  Overall looks good to me as well. As I understood the conversation on Slack, the magic is that POM's `<dependency>` entry is transformed based on the extra attribute information available in Maven properties in the case of sbt plugins. For future reference, could you add a note to that effect in the commit message please?

**Comment by adpi2** [comment]
I added a few more comments, and I rewrote the commit message.

Also I suggest we wait a bit before merging, until we agree on the implementation in https://github.com/coursier/coursier/pull/2633.

**Review by julienrf — APPROVED** [review]

**Comment by adpi2** [comment]
Coursier is now ready to resolve the new Maven pattern of sbt plugins:
- https://github.com/coursier/coursier/pull/2633
- https://github.com/coursier/sbt-coursier/pull/445
- https://github.com/coursier/sbt-coursier/releases/tag/v2.0.16

@eed3si9n If you agree, I need your :heavy_check_mark: to merge this PR.

**Review by eed3si9n — APPROVED** [review]
Thanks @adpi2!

**Pull request merged**
