### PR TITLE
Update to sbt/io v1.0.0-M1, cross build, setup Travis

### PR DESCRIPTION
**Pull request by Duhemm**
This cannot be built unless sbt/util has been published

### CODE REVIEW

**Comment by dwijnand** [comment]
Triggering Travis.

**Comment by eed3si9n** [comment]
```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scala-sbt.util#util-logging_2.10;1.0.0-SNAPSHOT: not found
[warn]  :: org.scala-sbt.util#util-collection_2.10;1.0.0-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]      org.scala-sbt.util:util-logging_2.10:1.0.0-SNAPSHOT (/home/travis/build/sbt/librarymanagement/build.sbt#L43)
[warn]        +- org.scala-sbt.librarymanagement:librarymanagement_2.10:1.0.0-SNAPSHOT
[warn]      org.scala-sbt.util:util-collection_2.10:1.0.0-SNAPSHOT (/home/travis/build/sbt/librarymanagement/build.sbt#L43)
[warn]        +- org.scala-sbt.librarymanagement:librarymanagement_2.10:1.0.0-SNAPSHOT
sbt.ResolveException: unresolved dependency: org.scala-sbt.util#util-logging_2.10;1.0.0-SNAPSHOT: not found
unresolved dependency: org.scala-sbt.util#util-collection_2.10;1.0.0-SNAPSHOT: not found
    at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:294)
```

**Comment by Duhemm** [comment]
@eed3si9n It looks like this is fixed (still fails because `util-*_2.11` has not been published).

**Comment by jsuereth** [comment]
basic gist LGTM once we fix travis by publishing util

**Comment by eed3si9n** [comment]
Closing this in favor of #2.

**Pull request closed without merging**
