### PR TITLE
Add EvictionWarningOptions.summary that tells the users to call "evicted"

### PR DESCRIPTION
**Pull request by exoego**
Partially addresses https://github.com/sbt/sbt/issues/3773

I followed the below note in the issue.

>  Next, we could add EvictionWarningOptions.summary that tells the users to call "evicted".

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=1.x&zinc=1.x&io=1.x&librarymanagement=pull/211/head&util=1.x&website=1.x&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/470/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: 1.x-1.x-1.x-pull/211/head-1.x-1.x)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/470/">has checked</A> the following projects against Scala 2.12, 2.11, 2.10,
tested using sbt-allsources.sh.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/1.x">1.x                 </A> | sbt/sbt@78f7658a67b2b3f597186207f1bdbfea67c0d313
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/1.x">1.x                 </A> | sbt/zinc@3c12aba4193b28fd16767c28a1cf8a1c3bbf91b8
  io                | <A HREF="https://github.com/sbt/io/tree/1.x">1.x                 </A> | sbt/io@7f8c185b4a522781d5b6dd21d3002a6bd8cfc08e
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/pull/211">pull/211/head       </A> | sbt/librarymanagement@091edf6ea1dc4533e6c55c0be725026516733bbb
  util              | <A HREF="https://github.com/sbt/util/tree/1.x">1.x                 </A> | sbt/util@9891f07bda2d7d44be141401ed29abe39d42a43a
  website           | <A HREF="https://github.com/sbt/website/tree/1.x">1.x                 </A> | sbt/website@5d5e3d57a7e078da65290334e701a02f46691d55

:white_check_mark: The result is: ***SUCCESS***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=1.x&zinc=1.x&io=1.x&librarymanagement=pull/211/head&util=1.x&website=1.x&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/472/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/473/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: 1.x-1.x-1.x-pull/211/head-1.x-1.x)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/473/">has checked</A> the following projects against Scala 2.12, 2.11, 2.10,
tested using sbt-allsources.sh.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/1.x">1.x                 </A> | sbt/sbt@78f7658a67b2b3f597186207f1bdbfea67c0d313
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/1.x">1.x                 </A> | sbt/zinc@3c12aba4193b28fd16767c28a1cf8a1c3bbf91b8
  io                | <A HREF="https://github.com/sbt/io/tree/1.x">1.x                 </A> | sbt/io@7f8c185b4a522781d5b6dd21d3002a6bd8cfc08e
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/pull/211">pull/211/head       </A> | sbt/librarymanagement@f8dbbd85b98e80e23faa5dec9191dd58dce5b2bc
  util              | <A HREF="https://github.com/sbt/util/tree/1.x">1.x                 </A> | sbt/util@9891f07bda2d7d44be141401ed29abe39d42a43a
  website           | <A HREF="https://github.com/sbt/website/tree/1.x">1.x                 </A> | sbt/website@5d5e3d57a7e078da65290334e701a02f46691d55

:white_check_mark: The result is: ***SUCCESS***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=1.x&zinc=1.x&io=1.x&librarymanagement=pull/211/head&util=1.x&website=1.x&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Review by eed3si9n — APPROVED** [review]
LGTM
Sorry about the delayed review

**Comment by dwijnand** [comment]
thanks @exoego!

**Pull request merged**
