### PR TITLE
Add file name to exception message

### PR DESCRIPTION
**Pull request by leonardehrenfried**
I'm currently running into the error described here: https://github.com/sbt/sbt/issues/3431

This PR adds more information to the error message so debugging is at least possible.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?librarymanagement=pull/171/head&deploy_to_bintray=false&run_sbt_community=false">this link.</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/201/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: 1.x-1.x-1.x-pull/171/head-1.x-1.x)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/201/">has checked</A> the following projects against Scala 2.12, 2.10,
tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/1.x">1.x                 </A> | sbt/sbt@9d8a041a06238d3db855ee88018d3aeceb5ff75f
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/1.x">1.x                 </A> | sbt/zinc@b63e9c6808ebd7eb5b511b9b9b7c0cf3a27cd896
  io                | <A HREF="https://github.com/sbt/io/tree/1.x">1.x                 </A> | sbt/io@62004b28dfcdc33273ebb07a563e78178f6eb21d
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/pull/171">pull/171/head       </A> | sbt/librarymanagement@08fedf787b490c736cc32025fd86ccbae732b33e
  util              | <A HREF="https://github.com/sbt/util/tree/1.x">1.x                 </A> | sbt/util@be73dc0a331a3b64994baa6267fdb2efea0fa925
  website           | <A HREF="https://github.com/sbt/website/tree/1.x">1.x                 </A> | 

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=1.x&zinc=1.x&io=1.x&librarymanagement=pull/171/head&util=1.x&website=1.x&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by leonardehrenfried** [comment]
The Travis build fails with
```
[info] ModuleResolversTest:
[info] The direct resolvers in update options
[info] - should skip the rest of resolvers *** FAILED ***
[info]   605 was not less than or equal to 581.6 (ModuleResolversTest.scala:48)
```
Is this something introduced by this commit?

**Comment by dwijnand** [comment]
Nope.

**Review by dwijnand — APPROVED** [review]

**Review by eed3si9n — APPROVED** [review]

**Comment by eed3si9n** [comment]
Changed based to 1.0.x.

**Pull request merged**
