### PR TITLE
Fix #275 - Publish back -tests jars for core and ivy modules

### LINKED ISSUE #275: Tests jar are no longer published on maven
Since librarymanagement 1.0.X, you do not publish any tests jar artifact on maven repositories

I used to extend some spec for unitary tests when i used librarymanagement 0.1.X 
you can take a look into :  https://repo1.maven.org/maven2/org/scala-sbt/librarymanagement_2.10/0.1.0-M9/ , which have tests jar published

And now :  https://repo1.maven.org/maven2/org/scala-sbt/librarymanagement-core_2.12/1.2.2/ tests jar are no longer published

Thanks for your help

### PR DESCRIPTION
**Pull request by Xephi**

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=develop&zinc=develop&io=develop&librarymanagement=pull/276/head&util=develop&website=develop&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1146/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: develop-develop-develop-pull/276/head-develop)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1146/">has checked</A> the following projects, tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/develop">develop             </A> | sbt/sbt@23063e2813c81daee64d31dd7760f5a4fae392e6
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/develop">develop             </A> | sbt/zinc@c8e1f5335552bae9a7623d92866a233598fad9fc
  io                | <A HREF="https://github.com/sbt/io/tree/develop">develop             </A> | sbt/io@e6529c010c32a93b66f96a027068b7cf160099a0
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/pull/276">pull/276/head       </A> | sbt/librarymanagement@48655bb7dc2bae19765ae627c359504b3986aaed
  util              | <A HREF="https://github.com/sbt/util/tree/develop">develop             </A> | sbt/util@cd679591d068c9863919feea4f363070c74f2774

:white_check_mark: The result is: ***SUCCESS***

The binaries are at https://dl.bintray.com/sbt/maven-snapshots
The new sbt version is: 1.3.0-bin-20181028T161712
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=develop&zinc=develop&io=develop&librarymanagement=pull/276/head&util=develop&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by eed3si9n** [comment]
See #275

**Pull request closed without merging**
