### PR TITLE
Replace conflictManager to conflictManagers, related to sbt/sbt#4318

### PR DESCRIPTION
**Pull request by elbakramer**
- `ModuleDescriptorConfiguration` now has multiple `conflictManagers` instead of single `conflictManager`.
- `IvySbt.setConflictManager` method is now renamed to `IvySbt.addConflictManager`.
- `Module.configureInline` method now adds multiple `conflictManager`s to `ModuleDescriptor`.
- This PR is related to sbt/sbt#4318

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=1.x&zinc=1.x&io=1.x&librarymanagement=pull/260/head&util=1.x&website=1.x&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/932/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/4318/head-1.x-1.x-pull/260/head-1.x-1.x)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/932/">has checked</A> the following projects against Scala 2.12,
tested using sbt-allsources.sh.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/pull/4318">pull/4318/head      </A> | sbt/sbt@c7a4d89c52fedff869cc688b583a4aa131244614
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/1.x">1.x                 </A> | sbt/zinc@c705199fe7387729a1c1a54b4ab2ac4e347b860a
  io                | <A HREF="https://github.com/sbt/io/tree/1.x">1.x                 </A> | sbt/io@36abd944e750c04d154b2c3218f4cc1a7e40a74a
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/pull/260">pull/260/head       </A> | sbt/librarymanagement@7dbc64d114198cbacf9105f4a1909045e558dd2e
  util              | <A HREF="https://github.com/sbt/util/tree/1.x">1.x                 </A> | sbt/util@39070c18e2280bb6532c13709bb12226259c2960
  website           | <A HREF="https://github.com/sbt/website/tree/1.x">1.x                 </A> | sbt/website@9e94e3f8ccad15543f843f2353b6998cfda5246e

:white_check_mark: The result is: ***SUCCESS***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=pull/4318/head&zinc=1.x&io=1.x&librarymanagement=pull/260/head&util=1.x&website=1.x&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Review by eed3si9n — CHANGES_REQUESTED** [review]
ModuleDescriptorConfiguration is part of the API, so we cannot break the binary compatibility. Maybe you can call it `additionalConflictManagers` or something and add a new field?

**Pull request closed without merging**
