### PR TITLE
Update to latest sbt-houserules, formatting

### PR DESCRIPTION
**Pull request by Duhemm**

### CODE REVIEW

**Comment by dwijnand** [comment]
:+1:

**Comment by eed3si9n** [comment]
The new houserules has many of the Bintray settings, so we should clean them up from build.sbt as well.

**Comment by Duhemm** [comment]
@eed3si9n Done

**Comment by dwijnand** [comment]
Also the licenses, developers and org can be dropped:
- https://github.com/sbt/sbt-houserules/blob/v0.2.1/src/main/scala/sbt/houserules/BintraySettingPlugin.scala#L17-L25
- https://github.com/sbt/sbt-houserules/blob/v0.2.1/src/main/scala/sbt/houserules/BuildPlugin.scala#L14

**Comment by Duhemm** [comment]
You're right, sorry. I just removed them.

**Comment by dwijnand** [comment]
Nice :+1:

**Pull request merged**
