### PR TITLE
[2.x] Merge develop into wip/sbt-2.x

### PR DESCRIPTION
**Pull request by adpi2**
We will probably need to release this to make https://github.com/sbt/sbt/pull/7554 compile and pass the test.

And we should do the same for Zinc.

### CODE REVIEW

**Comment by adpi2** [comment]
~~Blocked by https://github.com/eed3si9n/sjson-new/pull/134~~

**Comment by adpi2** [comment]
I cannot run the tests in https://github.com/sbt/sbt/pull/7573  because of https://github.com/eed3si9n/sbt-coursier/pull/1#issuecomment-2137292566. So maybe we should merge it, release it, and :crossed_fingers:.

**Review by eed3si9n — APPROVED** [review]
Thanks!

**Comment by adpi2** [comment]
Thanks for merging!

I will need a release of this to pursue the merge in `sbt-coursier` and `sbt`. Do you think I should use my own group ID (`ch.epfl.scala`) for releasing alpha versions?

**Pull request merged**
