### PR TITLE
Removed extra slash in the localBasePattern

### PR DESCRIPTION
**Pull request by laughedelic**
Fixes https://github.com/sbt/sbt/issues/3573 and https://github.com/ohnosequences/sbt-s3-resolver/issues/52.

When the `scala_[scalaVersion]/` segment (and/or the `PluginPattern` part) is present and the `/[branch]` segment isn't, an extra slash appears before `/[revision]`. This may cause some problem (see the linked issues).

Here is a comparison of the `localBasePattern` in sbt 0.13 vs 1.0+:

```
[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext])
[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)(/[branch])/[revision]/[type]s/[artifact](-[classifier]).[ext])
                                                                             ^
```

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?librarymanagement=pull/170/head&deploy_to_bintray=false&run_sbt_community=false">this link.</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/192/console">is in progress...</a>

**Comment by laughedelic** [comment]
Another related thing that I would change here:

https://github.com/laughedelic/librarymanagement/blob/364ba9b44b676012ab655c3dae9d894a16bd6a84/core/src/main/scala/sbt/librarymanagement/ResolverExtra.scala#L349-L350

If both `normBase` and `pattern` have slashes, it could produce `base//pattern`. So this `if` could be rewritten as 
```scala
normBase.stripSuffix("/") + pattern.stripPrefix("/")
```

Although it still doesn't cover the case when any of them has more than one slash before you concatenate them.

**Comment by typesafe-tools** [comment]
[//]: # (Refs: 1.x-1.x-1.x-pull/170/head-1.x-1.x)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/192/">has checked</A> the following projects against Scala 2.12,
tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/1.x">1.x                 </A> | sbt/sbt@4b8d31a9ea861e14922c640d1aa3935a7f33a8fb
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/1.x">1.x                 </A> | sbt/zinc@32e106d62abd8501863dbaa0d08a53cab4cf64e1
  io                | <A HREF="https://github.com/sbt/io/tree/1.x">1.x                 </A> | sbt/io@62004b28dfcdc33273ebb07a563e78178f6eb21d
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/pull/170">pull/170/head       </A> | sbt/librarymanagement@364ba9b44b676012ab655c3dae9d894a16bd6a84
  util              | <A HREF="https://github.com/sbt/util/tree/1.x">1.x                 </A> | sbt/util@cba6f83447b84cc1e967f25a930d4f411f6f0664
  website           | <A HREF="https://github.com/sbt/website/tree/1.x">1.x                 </A> | 

:white_check_mark: The result is: ***SUCCESS***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=1.x&zinc=1.x&io=1.x&librarymanagement=pull/170/head&util=1.x&website=1.x&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Review by eed3si9n — APPROVED** [review]
Nice fix.
I'm targeting this to 1.0.x branch

**Comment by laughedelic** [comment]
Cool 👍

**Pull request merged**
