### PR TITLE
Update util to 0.1.0-M8

### PR DESCRIPTION
**Pull request by eed3si9n**

### CODE REVIEW

**Comment by Duhemm** [comment]
LGTM

**Comment by Duhemm** [comment]
I spoke too fast, I'll update `.travis.yml`

**Comment by Duhemm** [comment]
I can't update directly this PR. There are 2 missing changes:
- In `build.sbt`
- In `.travis.yml`.

**Comment by eed3si9n** [comment]
@Duhemm I just gave you write rights.

**Comment by Duhemm** [comment]
Thanks! I've updated the PR

**Pull request merged**
