### PR TITLE
avoid deadlocks on spotty connections

### PR DESCRIPTION
**Pull request by OlegYch**
fix https://github.com/sbt/sbt/issues/3738

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?librarymanagement=pull/204/head&deploy_to_bintray=false&run_sbt_community=false">this link.</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/391/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: 1.x-1.x-1.x-pull/204/head-1.x-1.x)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/391/">has checked</A> the following projects against Scala 2.12, 2.11,
tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/1.x">1.x                 </A> | sbt/sbt@8067edbd8a15051c8cd3c6d66b399f2f79e2a94d
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/1.x">1.x                 </A> | sbt/zinc@2fade533ea7a6f28c5ddd1a0f23e9a03358cab44
  io                | <A HREF="https://github.com/sbt/io/tree/1.x">1.x                 </A> | sbt/io@f1077f0624c85f755241bd75626f9d843a165d59
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/pull/204">pull/204/head       </A> | sbt/librarymanagement@b5269cdcfa80720651f6ce28917bfe8f5e3b3bc4
  util              | <A HREF="https://github.com/sbt/util/tree/1.x">1.x                 </A> | sbt/util@2022713ff50d46849a4b1c93ec571287814c7055
  website           | <A HREF="https://github.com/sbt/website/tree/1.x">1.x                 </A> | 

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=1.x&zinc=1.x&io=1.x&librarymanagement=pull/204/head&util=1.x&website=1.x&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by dwijnand** [comment]
Hey @OlegYch, do you think it would be possible to create a regression test for this?

**Comment by OlegYch** [comment]
@dwijnand this depends on external wonky services, so it would be hard to create a reliable testcase
alternatively a mock broken resolver could be used, but i'm not sufficiently familiar with ivy

**Comment by dwijnand** [comment]
Fair enough.

Then I think we should at least leave some explanatory comments in code about this fix.

**Comment by OlegYch** [comment]
@dwijnand added a comment

**Review by dwijnand — DISMISSED** [review]
Thanks. LGTM.

**Comment by dwijnand** [comment]
Do you mind rebasing this onto 1.1.x please? That way we might be able to ship this in sbt 1.1.1.

**Review by dwijnand — APPROVED** [review]

**Comment by OlegYch** [comment]
@dwijnand thanks, apparently i don't know how to rebase

**Comment by dwijnand** [comment]
np

**Review by eed3si9n — APPROVED** [review]

**Pull request merged**
