### PR TITLE
Offload downloading to a separate thread pool to fix performance issue

### PR DESCRIPTION
**Pull request by OlegYch**
Fixes https://github.com/sbt/sbt/issues/4224

blocking+global ec+par collections leads to a significant performance regression, offload downloading to a separate threadpool

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=1.1.x&zinc=1.1.x&io=1.1.x&librarymanagement=pull/249/head&util=1.1.x&website=1.1.x&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Review by eed3si9n — APPROVED** [review]
Thanks for the prompt fix. LGTM

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/830/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: 1.1.x-1.1.x-1.1.x-pull/249/head-1.1.x-1.1.x)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/830/">has checked</A> the following projects against Scala 2.12,
tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/1.1.x">1.1.x               </A> | sbt/sbt@21db2867664cd8f21a1738147b88895fac73673a
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/1.1.x">1.1.x               </A> | sbt/zinc@899d7bd0282cf1ca2c0d3704ddb242bea30007e3
  io                | <A HREF="https://github.com/sbt/io/tree/1.1.x">1.1.x               </A> | sbt/io@1534128a10c3ae6c9f532432c95fa3440d755de5
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/pull/249">pull/249/head       </A> | sbt/librarymanagement@a8d5db4fb6346d784112c518e26a149a38ac6ea4
  util              | <A HREF="https://github.com/sbt/util/tree/1.1.x">1.1.x               </A> | sbt/util@d40517b8280734ed236199a9cb8793c153597026
  website           | <A HREF="https://github.com/sbt/website/tree/1.1.x">1.1.x               </A> | 

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=1.1.x&zinc=1.1.x&io=1.1.x&librarymanagement=pull/249/head&util=1.1.x&website=1.1.x&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by OlegYch** [comment]
@eed3si9n 
```
[sbt212] [info] ! Key parser test.An unspecified project axis resolves to the current project: Falsified after 22 passed tests.
[sbt212] [info] > Labels of failing property: 
[sbt212] [info] Parsed: Right(ProjectRef(uri("m:gwDk#hrkqzq"), "nf") / lv)
```
seems like an unrelated regression

**Comment by eed3si9n** [comment]
> seems like an unrelated regression

Yea. There's a known issue with slash testing.

**Pull request merged**
