### PR TITLE
Set Gigahorse readTimeout to 1 hour

### PR DESCRIPTION
**Pull request by peterneyens**
Following the suggestion made by @eed3si9n in https://github.com/sbt/sbt/issues/4199:
- Use the `HttpClient` from `core` in `ivy`.
- Configure Gigahorse to use a `readTimeout` of 60 minutes.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=1.x&zinc=1.x&io=1.x&librarymanagement=pull/246/head&util=1.x&website=1.x&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Review by eed3si9n — APPROVED** [review]
Nice.

**Comment by eed3si9n** [comment]
@peterneyens Thanks for the contribution!

**Comment by peterneyens** [comment]
Should I squash the two commits?

**Comment by eed3si9n** [comment]
Yes, plz.

**Pull request merged**
