### PR TITLE
Add OkHttpClient parameter

### PR DESCRIPTION
**Pull request by eed3si9n**
Ref #297

This adds a parameter so we can pass in OkHttpClient, if someone wants to customize HTTP behavior.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=develop&zinc=develop&io=develop&librarymanagement=pull/298/head&util=develop&website=develop&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Comment by eatkins** [comment]
Not sure what the dependency story is with library management, but it would it be possible to define a simple interface that mirrors the OkHttpClient api so that we don't add an explicit reference to OkHttpClient in the api?

**Comment by eed3si9n** [comment]
@eatkins Gigahorse is that, an abstraction of HTTP client, but the interesting feature that would make it useful to customize the HTTP client beyond what's there out of the box is in the underlying OkHttpClient (and/or its builder).

**Comment by eatkins** [comment]
This feels almost directly in opposition to https://github.com/sbt/sbt/issues/4597. My concern is that what if someone wants to use a different version of okhttpclient than what lm is using? This would introduce classpath eviction issues.

**Comment by eatkins** [comment]
More generally, my philosophy is that unless a library is designed to directly enhance some other library, it should hide its dependencies.

**Comment by eed3si9n** [comment]
Discussed this during the sbt meeting today. We can probably merge this to LM, but potentially hide the extension points in sbt behind some experimental plugin.

**Pull request merged**
