### PR TITLE
Improve config-creating macro error message

### LINKED ISSUE #130: Improve macro error message
## steps

Use config inline.

##  problem

```
config must be directly assigned to a val, such as `val x = config`.
```

This is typically not how you define a config.

## expectation

```
config must be directly assigned to a val, such as `val Tooling = config("tooling")`
```

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes #130

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?librarymanagement=pull/131/head&deploy_to_bintray=false">this link.</A>

**Review by Duhemm — APPROVED** [review]

**Comment by dwijnand** [comment]
Where's my gold medal for messing up a 1-line string change PR?

**Comment by Duhemm** [comment]
What was the error? I missed it too.

**Comment by dwijnand** [comment]
I was missing a final `)` to make it compile :)

**Comment by Duhemm** [comment]
You win the medal then, my 2 characters change only muted sbt 😇

**Review by eed3si9n — APPROVED** [review]
LGTM pending Travis

**Pull request merged**
