### PR TITLE
Avoid java.net.URL

### PR DESCRIPTION
**Pull request by jtjeferreira**
I was using sbt without internet connection and noticed that `update` task taking a lot of time (around 30s). I did a thread dump with a `SigQuit` ( `Ctrl` + `\`) and noticed that the thread was blocked because `java.net.URL#equals` blocks:

```
"pool-514-thread-3" #918 prio=5 os_prio=31 cpu=292.62ms elapsed=128.20s tid=0x000000012d484a00 nid=0x1071b waiting for monitor entry  [0x0000000175550000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.net.InetAddress$NameServiceAddresses.get(java.base@17.0.10/InetAddress.java:838)
	- waiting to lock <0x0000000737d5e758> (a java.net.InetAddress$NameServiceAddresses)
	at java.net.InetAddress.getAllByName0(java.base@17.0.10/InetAddress.java:1533)
	at java.net.InetAddress.getAllByName(java.base@17.0.10/InetAddress.java:1385)
	at java.net.InetAddress.getAllByName(java.base@17.0.10/InetAddress.java:1306)
	at java.net.InetAddress.getByName(java.base@17.0.10/InetAddress.java:1256)
	at java.net.URL.getHostAddress(java.base@17.0.10/URL.java:831)
	- locked <0x00000007073fd680> (a java.net.URL)
	at java.net.URLStreamHandler.getHostAddress(java.base@17.0.10/URLStreamHandler.java:447)
	at java.net.URLStreamHandler.hostsEqual(java.base@17.0.10/URLStreamHandler.java:459)
	at java.net.URLStreamHandler.sameFile(java.base@17.0.10/URLStreamHandler.java:431)
	at java.net.URLStreamHandler.equals(java.base@17.0.10/URLStreamHandler.java:352)
	at java.net.URL.equals(java.base@17.0.10/URL.java:980)
	at scala.runtime.BoxesRunTime.equals2(BoxesRunTime.java:137)
	at scala.runtime.BoxesRunTime.equals(BoxesRunTime.java:123)
	at scala.Some.equals(Option.scala:513)
	at sbt.librarymanagement.Artifact.equals(Artifact.scala:22)
	at scala.runtime.BoxesRunTime.equals2(BoxesRunTime.java:137)
	at scala.runtime.BoxesRunTime.equals(BoxesRunTime.java:123)
	at scala.Tuple2.equals(Tuple2.scala:24)
	at scala.runtime.BoxesRunTime.equals2(BoxesRunTime.java:137)
	at scala.runtime.BoxesRunTime.equals(BoxesRunTime.java:123)
	at scala.collection.IterableLike.sameElements(IterableLike.scala:304)
	at scala.collection.IterableLike.sameElements$(IterableLike.scala:294)
	at scala.collection.AbstractIterable.sameElements(Iterable.scala:56)
	at scala.collection.GenSeqLike.equals(GenSeqLike.scala:481)
	at scala.collection.GenSeqLike.equals$(GenSeqLike.scala:480)
	at scala.collection.AbstractSeq.equals(Seq.scala:45)
	at sbt.librarymanagement.ModuleReport.equals(ModuleReport.scala:34)
	at scala.runtime.BoxesRunTime.equals2(BoxesRunTime.java:137)
	at scala.runtime.BoxesRunTime.equals(BoxesRunTime.java:123)
	at scala.collection.IterableLike.sameElements(IterableLike.scala:304)
	at scala.collection.IterableLike.sameElements$(IterableLike.scala:294)
	at scala.collection.AbstractIterable.sameElements(Iterable.scala:56)
	at scala.collection.GenSeqLike.equals(GenSeqLike.scala:481)
	at scala.collection.GenSeqLike.equals$(GenSeqLike.scala:480)
	at scala.collection.AbstractSeq.equals(Seq.scala:45)
	at sbt.librarymanagement.ConfigurationReport.equals(ConfigurationReport.scala:21)
```

In this PR I replaced `java.net.URL` with `java.net.URI` but kept the field names(i.e I didn't rename `url` to `uri`, or `browseUrl` to `browseUri`)

### CODE REVIEW

**Comment by jtjeferreira** [comment]
@adpi2 can you review this PR? I rebase after your changes were merged

**Review by adpi2 — COMMENTED** [review]
LGTM!

@eed3si9n What do you think? Is it okay to break the source compat on `Artifact.url` between 1.x and 2.x? There are probably many plugins that depend on `Artifact` but maybe not so many on `Artifact.url`. Not even [this one](https://github.com/scalacenter/sbt-dependency-submission).

**Review by eed3si9n — APPROVED** [review]
LGTM

**Comment by jtjeferreira** [comment]
> LGTM

The test failures are normal?

**Comment by jtjeferreira** [comment]
> > LGTM
> 
> The test failures are normal?

Thanks for rerunning the test @adpi2.  `CI / test (ubuntu-latest, 17, 1) ` is now green, but I think you have to rerun the other 2 ( `CI / test (ubuntu-latest, 11, 1) ` and `CI / test (ubuntu-latest, 8, 1) ` )

**Comment by adpi2** [comment]
> Thanks for rerunning the test @adpi2. CI / test (ubuntu-latest, 17, 1)  is now green, but I think you have to rerun the other 2 ( CI / test (ubuntu-latest, 11, 1)  and CI / test (ubuntu-latest, 8, 1)  )

I don't know why they appear as cancelled. But I think they were green before so let's just merge the PR.

**Comment by eed3si9n** [comment]
I guess we haven't bumped LM in a while in sbt/sbt, so I just realized that when trying to use this, we get
```scala
[info] [info] welcome to sbt 2.0.0-alpha12-SNAPSHOT (Azul Systems, Inc. Java 1.8.0_402)
[info] [info] loading project definition from /private/var/folders/hg/2602nfrs2958vnshglyl3srw0000gn/T/sbt_3624414e/project
[info] [error] java.lang.ClassCastException: java.net.URL cannot be cast to java.net.URI
[info] [error] 	at sjsonnew.IsoString$$anon$1.to(IsoString.scala:26)
[info] [error] 	at sjsonnew.IsoFormats$$anon$2.write(IsoFormats.scala:31)
[info] [error] 	at sjsonnew.StandardFormats$OptionFormat.write(StandardFormats.scala:37)
[info] [error] 	at sjsonnew.StandardFormats$OptionFormat.addField(StandardFormats.scala:44)
[info] [error] 	at sjsonnew.StandardFormats$OptionFormat.addField(StandardFormats.scala:40)
[info] [error] 	at sjsonnew.Builder.addField(Builder.scala:43)
[info] [error] 	at sbt.librarymanagement.ArtifactFormats$$anon$1.write(ArtifactFormats.scala:36)
[info] [error] 	at sbt.librarymanagement.ArtifactFormats$$anon$1.write(ArtifactFormats.scala:29)
```

https://github.com/sbt/sbt/issues/7720

**Pull request merged**
